### ISSUE TITLE
Ошибка при проверке state

### ISSUE THREAD

**Issue by Grinv** [zefirka/reduxto#6]
https://github.com/zefirka/reduxto/blob/7e54d8e1b8a4559d48a6e088b59d63fcaf914850/src/utils.js#L12

Если в `state` приходит `null`, валидация
```javascript
if (typeof state === 'object') { ... }
```
проходит успешно и при вызове
```javascript
Object.entries(state);
```
Происходит ошибка `Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by zefirka** [comment]
Fixed in [bf79ae](https://github.com/zefirka/reduxto/commit/bf79ae9c97c0b5dcab751c39206859175a2f84c8)
